### ISSUE TITLE
im hoping im just dumb

### ISSUE THREAD

**Issue by WrongBackGround** [pikdum/steam-deck#2] opened 2023-04-18 23:27 UTC
on steamdeck, in desktop mode, when i double click on the pikdum-vortex.desktop shortcut it opens the gray loading window and then just closes. did i miss something?

**Comment by pikdum** [comment] 2023-04-18 23:52
The loading window with the Vortex logo, or does it not even get to that point?

**Comment by WrongBackGround** [comment] 2023-04-18 23:58
its a steam tinker launch window, says something about preparing games

**Comment by pikdum** [comment] 2023-04-19 00:07
Interesting.

Some terminal commands you could try:

Remove Vortex and re-install:

```shell
# delete vortex
rm -rf ~/.config/steamtinkerlaunch/vortex/
# re-install vortex
~/stl/prefix/steamtinkerlaunch vortex install
# launch vortex through stl
~/stl/prefix/steamtinkerlaunch vortex start
```

If that doesn't work, could nuke my tools + stl, and try from scratch:

```shell
# delete stl
rm -rf ~/.config/steamtinkerlaunch/
rm -rf ~/stl/
# delete my tools
rm -rf ~/.pikdum/
# manually remove desktop icons and reinstall
```

Other than that, don't really have any ideas.
It's hard to debug Vortex startup issues because we're not getting any useful output.

**Comment by WrongBackGround** [comment] 2023-04-19 00:11
i have already deleted at the files, then downloaded a fresh install link. this second time it did not put the install vortex shortcut on the desktop. third times a charm?

**Comment by WrongBackGround** [comment] 2023-04-19 00:14
it didnt make the install vortex shortcut again

**Comment by pikdum** [comment] 2023-04-19 00:18
Delete `$HOME/.local/share/applications/pikdum-vortex.desktop` as well:

```shell
rm -rf $HOME/.local/share/applications/pikdum-vortex.desktop
```

Then you should get the install vortex shortcut after updating.

**Comment by WrongBackGround** [comment] 2023-04-19 00:20
![image](https://user-images.githubusercontent.com/131211610/232933714-d880e69c-6f08-4ff4-a3c1-b9895278ac67.png)
is this expected?

**Comment by pikdum** [comment] 2023-04-19 00:25
`~/stl/prefix/steamtinkerlaunch vortex install`?

**Comment by pikdum** [comment] 2023-04-19 00:27
If it's still running, it might be fine.
Installing Vortex does take a while, since it needs to download + install a bunch of .NET dependencies.

Another thing you could try is restarting, and then trying those commands I gave above to delete + re-install.
Could be some issues with `wineserver`.

**Comment by WrongBackGround** [comment] 2023-04-19 00:28
could wine/proton tricks be conflicting with it?

**Comment by WrongBackGround** [comment] 2023-04-19 00:41
the steam tinker launch progress bars dont progress

**Comment by pikdum** [comment] 2023-04-19 00:47
> could wine/proton tricks be conflicting with it?

Don't think so.

> the steam tinker launch progress bars dont progress

For installing Vortex? Yeah, they don't really.

**Comment by WrongBackGround** [comment] 2023-04-19 01:01
![image](https://user-images.githubusercontent.com/131211610/232939196-922d9b25-a338-40ab-b4bf-3704aa9ce08e.png)
this is all that shows up

**Comment by pikdum** [comment] 2023-04-19 01:55
Weird, that makes it look like it's running.

**Comment by pikdum** [comment] 2023-04-19 23:58
@WrongBackGround Should have a fix, see https://github.com/pikdum/steam-deck/issues/3#issuecomment-1515523080

**Comment by pikdum** [comment] 2023-04-20 00:10
Fix confirmed to work, closing.

**Comment by pikdum** [comment] 2023-04-20 00:25
Actually, will leave open until you've confirmed it's fixed as well.

**Comment by sonic2kk** [comment] 2023-04-20 01:17
Hello! STL maintainer here, just chiming into say that this is almost certainly an issue with Wine and Vortex. There have been no real changes to Vortex support in STL, the last one was probably a few months ago related to the `.desktop` files.

There is not a whole lot I or pikdum can do about this. It is possible that there is a Winetrick which could be installed to resolve the issue, but I am not aware of any.

I think there is a Lutris install script for Vortex, it may be worth tracking online how other Vortex implementations resolve this issue, if/when they do. But I would say this is probably an issue related to Wine/Vortex. It may be worth reporting upstream to Wine on WineHQ, or to Vortex (or both).

**Comment by pikdum** [comment] 2023-04-20 01:25
> There is not a whole lot I or pikdum can do about this.

Right, https://github.com/pikdum/steam-deck/commit/7dbec5dfc387e45132d309deca471c7f9b529d75 is just a quick fix to stay on Vortex 1.7.8 instead of latest.
Should be fine for a bit since 1.8.0 is still a pre-release, but I'll still need to look into a proper fix for 1.8.0 support eventually.

**Comment by sonic2kk** [comment] 2023-04-20 01:36
The pre-release channel is meant to be a separate option, but maybe Vortex changed something and that option isn't working currently. I'll need to investigate that (tbh, I don't like Vortex so I have not spent much time looking at the code at it, it has been mostly untouched since I took over).

**Comment by WrongBackGround** [comment] 2023-04-20 01:54
it seems to have done the trick, thanks a million

**Comment by pikdum** [comment] 2023-04-20 02:20
Closing, since the fix worked.

Created https://github.com/pikdum/steam-deck/issues/4 to track proper Vortex 1.8 support.

**Closed by pikdum** 2023-04-20 02:20 UTC
