### ISSUE TITLE
cant install dotnet

### ISSUE THREAD

**Issue by gleipy** [pikdum/steam-deck#7] opened 2023-05-10 16:23 UTC
I'm in stable channel, I had it installed and uninstalled, now when I install it again, it stuck at installing dotnet and once it's completed and there's message saying vortex cant run without .net
![IMG_20230510_232240](https://github.com/pikdum/steam-deck/assets/67846358/7c6b3904-9df1-4e1c-a8b0-24b859234951)

**Comment by Afrodinho** [comment] 2023-05-10 17:58
Currently having this same issue. 

This is what I have tried so far:

### Leaving this screen up and running - 

This happened Once
> Leads to this completing? The screen goes away then I can click on Vortex on the desktop to launch it. However Vortex doesn't function properly. It doesn't launch. I did manage to get it to launch once. However Vortex told me that it required donet in order to run and prompted me to download.  I did this and was met with the same prompt to download dotnet again.

Most Common Outcome
> When I wait long enough and wait for the dotnet screen to go away, it seems like everything worked. Vortex appears on the desktop. Sometimes when attempting to launch, SteamTinkerLaunch prompts appear in the notification bar like normal. If I check my system monitor Vortex will sometimes appear using around 1.3 GiB of memory. No matter how long I wait nothing changes though. The application doesn't seem to launch. Most of the time however, Vortex appears in my System monitor for around 5 second and disappears. Obviously meaning that it is no longer running. 


### Completely deleting and re installing -

 https://github.com/pikdum/steam-deck/issues/2#issuecomment-1513931052

Used this guide and ran these in the Konsole. The commands worked when deleting the files.
Tried to reinstall and was met with the same issue.  Stuck on dotnet.

Tried to manually uninstall and then tried to reinstall. Still stuck on dotnet.


I hope that this can help you look into this issue.

**Comment by sonic2kk** [comment] 2023-05-11 18:44
You're free to contribute to upstream STL if you'd like as well 😄 Usually these breakages come from Vortex breaking under Wine and resolve themselves with Vortex updates.

I don't use Vortex and it might be better to remove STL as a dependency but an improvement to Vortex in STL from someone who uses Vortex would be welcome.

**Comment by pikdum** [comment] 2023-05-11 18:55
I think the main things would be:
1. Vortex's tech stack moves quickly, so needs an up-to-date Wine that can handle latest .NET and Electron
2. Vortex can install .NET itself, which seems more consistent

Doing the first in STL might be a bit tricky, though

**Comment by sonic2kk** [comment] 2023-05-11 19:31
1. Users can update the Wine version that Vortex uses in the Global Menu, so that's not really an issue.
2. Vortex relies on .NET 4.8 to install from what I recall, and then also requires .NET 6. When it tries to install .NET itself, it won't *fail* as such (in my experience), but if Vortex doesn't see .NET 4.8 from Winetricks, it won't see it when it tries to install .NET itself.

**Comment by pikdum** [comment] 2023-05-11 19:50
> Users can update the Wine version that Vortex uses in the Global Menu, so that's not really an issue.

Feels like an issue when things are broken with the default version.
I can't really expect users of this tool to understand how to tinker with STL either, since this should 'just work'.

> Vortex relies on .NET 4.8 to install from what I recall

From playing around a bit, seems like Vortex doesn't require anything just to install anymore.

**Comment by pikdum** [comment] 2023-05-12 05:03
> Back when an issue very similar to this one was reported to STL I tested if .NET was required and it was, but that was 5-6 months ago or so. It would be a relief if it could be removed!

Seems to be not required with version 1.8, and after install Vortex can set up .NET 6 itself.
Still required for version 1.7, otherwise Vortex shows a warning at startup.

I'm pretty lost at this point, but here's some observations:
1. Vortex 1.8 is broken on GE-Proton7-55
2. GE-Proton8-x is broken through STL on my Steam Deck - this is why Dotnet install (and everything else?) is hanging
3. Vortex 1.8 runs great on Wine-GE-Proton8-5, on my Linux desktop, using my new scripts
4. Wine-GE-Proton8-5 is broken through my new scripts on my Steam Deck too :^)

Pushed a fix here that:
* installs GE-Proton7-55 for STL
* sets USEVORTEXPROTON="GE-Proton7-55"
* as before, installs Vortex 1.7.8 instead of 1.8.x

@gleipy 
@Afrodinho 
If you guys want to try the fix and let me know if it works, there are some manual steps required:

1. wipe existing install:
  ```bash
   rm -rf ~/stl ~/.config/steamtinkerlaunch/ ~/.local/share/applications/pikdum-vortex.desktop
   ```
2. run "Update Pikdum's Tools" to get the new changes
3. run "Install Vortex"
4. once in Vortex, make sure to turn off automatic updates so it doesn't try to update to v1.8.x and break again

Let me know if it works.

I have no idea why I can't get GE-Proton8-x working on my Steam Deck, but that's probably a requirement for getting Vortex v1.8.x to run.

**Comment by Afrodinho** [comment] 2023-05-12 05:22
I can confirm this works. Did everything you said and Vortex was installed in less than 5 minutes. It installed .net just fine. Nexus links are being handled and downloading like normal as well! Thank You!

**Comment by sonic2kk** [comment] 2023-05-12 12:46
Great investigation, thanks! It seems Steam Deck is the problem here, if I'm understanding correctly GE-Proton works to run Vortex on Linux Desktop but not on Steam Deck.

> Seems to be not required with version 1.8, and after install Vortex can set up .NET 6 itself.

So the logic around installing dotnet48 and .NET 6 is no longer required? That would be great honestly, and I can look into removing it. I don't know if that'll necessarily help anything already but it would be nice to remove, it should even speed up start time.

If you have code handy that does this already or if you would like you're free to open a PR (you might be more familiar with the requirements for Vortex than me) but there's no worries if you can't or simply don't want to, I can do it when I have some time hopefully over the weekend!

> I have no idea why GE-Proton8-x isn't working on Steam Deck, but that's probably what we need for Vortex v1.8.x to run.

This is just a shot-in-the-dark, but talking from experience, .NET stuff tends to not work very well on Steam Deck (people who use "trainer" tools which require DotNet report various issues, HMM does not reliably install on Steam Deck, etc). I'm not sure why this is, so apologies that I can't help further, just wanted to mention that I've seen people complain about .NET under Wine on SteamOS specifically a lot more than other distros (but SteamOS is also more prominent, so that may be why 🤓)

<hr>

As a somewhat note-to-self, this recent breakage with Vortex has put two things in my mind:
1. Implement the logic in STL that should only download stable or beta builds (there's a setting but the logic was apparently never implemented and was added around 2 years ago! I don't know how to implement this or if there's a straightforward way to do so, but I'd like to do this). May not be helpful directly to this project but could prevent beta updates that may not work properly under Wine yet 
2. Add an option to disable Vortex auto updates, maybe STL can overwrite a Vortex config file if there's an easy value that can be adjusted for this somewhere in a settings file. No idea how feasible this is to do (if Vortex writes to some browser cache that isn't plaintext, this may be tricky to do with Bash)

**Comment by pikdum** [comment] 2023-05-12 23:31
> if I'm understanding correctly GE-Proton works to run Vortex on Linux Desktop but not on Steam Deck

I was using Wine-GE-Proton instead of GE-Proton, so I'm not 100% sure if GE-Proton works.

**Comment by sonic2kk** [comment] 2023-05-13 20:08
> This would be neat, I was thinking of trying the same.

Just found a way to do it, turns out STL already does this for quite a few things with Vortex using the executable's `--set` option to set config options. So we can manually set the release channel like this:

```bash
# Can be 'stable', 'beta', or 'none'
NEXUPDATECHANNEL="none"
setVortSet "settings.update.channel=\"\\\"$NEXUPDATECHANNEL\\\"\""
```

I think the next steps for STL are:
- Default to only downloading the latest stable Vortex
- Implement functionality for the Vortex Pre-Release checkbox
- Add a checkbox for "No automatic updates" on the Global Menu, which will be set each time Vortex launches - This will override user-changed preferences inside of Vortex at launch if this STL option is enabled but this would be expected behaviour
- Once 1.8 is stable, experimentally remove the .NET installation code :-)

The tricky parts will be implementing the first two as I am not sure how to filter the releases at time of writing. However, the rest should be fairly straightforward.

**Comment by pikdum** [comment] 2023-05-13 20:14
Closing since the original issue was resolved.

**Closed by pikdum** 2023-05-13 20:14 UTC

**Comment by sonic2kk** [comment] 2023-05-26 12:32
Sorry to bump a closed issue but all of the improvements outlined from my previous comment are now part of STL, as well as an option to specify a Vortex version to use from the UI and command-line. Thought it might be useful to give an update :-)

**Comment by pikdum** [comment] 2023-05-26 21:41
Awesome, thanks! I'll look into getting those integrated here.
